language: ruby
rvm:
  - "1.9.3"
branches:
  only:
    - master
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - bundle exec rake --trace db:migrate
  - bundle exec rspec spec/
bundler_args: --without development
before_script:
  - mysql -e 'create database triage_test'
  - psql -c 'create database triage_test' -U postgres
