development:
  host: localhost
  port: 1389
  attribute: cn
  base: ou=people,dc=test,dc=com
  ssl: false

production:
  host: localhost
  port: 636
  attribute: cn
  base: ou=people,dc=test,dc=com
  ssl: start_tls
